eureka:
  instance:
    hostname: config-service
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
spring:
  cloud:
    config:
      override-system-properties: false
server:
  port: 8888