spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kenac_banking_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 5092

application:
  config:
    client-url: http://localhost:5980/client
    auth-url: http://localhost:5980/auth