spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5441/kenac_customer_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5091

application:
  config:
    banking-url: http://gateway-service:5980/banking
    auth-url: http://gateway-service:5980/auth