spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
      routes:
        - id: client-service
          uri: lb:http://CLIENT-SERVICE
          predicates:
            - Path=/client/**
        - id: banking-service
          uri: lb:http://BANKING-SERVICE
          predicates:
            - Path=/banking/**
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/auth/**

server:
  port: 5980