# application.yml (for config service)
eureka:
  instance:
    hostname: config-service
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
spring:
  cloud:
    config:
      override-system-properties: false
server:
  port: 8888

---
# auth-service.yml
spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/kenac_auth_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5093

application:
  security:
    jwt:
      secret-key: key
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  config:
    client-url: http://gateway-service:5980/client
    banking-url: http://gateway-service:5980/banking

---
# banking-service.yml
spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/kenac_banking_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5092

application:
  config:
    client-url: http://gateway-service:5980/client
    auth-url: http://gateway-service:5980/auth

---
# client-service.yml
spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/kenac_customer_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5091

application:
  config:
    banking-url: http://gateway-service:5980/banking
    auth-url: http://gateway-service:5980/auth

---
# discovery-service.yml
eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 8761

---
# gateway-service.yml
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/client/**
        - id: banking-service
          uri: lb://BANKING-SERVICE
          predicates:
            - Path=/banking/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

server:
  port: 5980