version: '3.9'

services:

  config-service:
    build: ./services/config-service
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - kenac-net

  discovery-server:
    build: ./services/discovery-server
    ports:
      - "8761:8761"
    networks:
      - kenac-net
    depends_on:
      - config-service

  gateway-service:
    build: ./services/gateway-service
    ports:
      - "5980:5980"
    networks:
      - kenac-net
    depends_on:
      - config-service
      - discovery-server

  auth-service:
    build: ./services/auth-service
    ports:
      - "5090:5090"
    networks:
      - kenac-net
    depends_on:
      - discovery-server
      - config-service
      - postgres

  client-service:
    build: ./services/client-service
    ports:
      - "5091:5091"
    networks:
      - kenac-net
    depends_on:
      - discovery-server
      - config-service
      - postgres

  banking-service:
    build: ./services/banking-service
    ports:
      - "5092:5092"
    networks:
      - kenac-net
    depends_on:
      - discovery-server
      - config-service
      - postgres

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5441:5432"
    networks:
      - kenac-net

volumes:
  postgres_data:

networks:
  kenac-net:
